# SPDX-License-Identifier: GPL-2.0

sun50i-h713-av1-objs := sun50i-h713-av1.o \
			 sun50i-h713-av1-hw.o \
			 sun50i-h713-av1-v4l2.o \
			 sun50i-h713-av1-debugfs.o

obj-$(CONFIG_VIDEO_SUN50I_H713_AV1) += sun50i-h713-av1.o